charts/mapgl-js-api/Chart.yaml, charts/mapgl-js-api/README.md, charts/mapgl-js-api/templates/NOTES.txt, charts/mapgl-js-api/templates/deployment.yaml, charts/mapgl-js-api/values.yaml
Добавил префикс для переменных PUBLIC_HOST и DEMO_KEY
Немного поправил README
=> Префикс MAPGL_ для переменных PUBLIC_HOST и DEMO_KEY

charts/proxy-traffic-jams/Chart.yaml, charts/proxy-traffic-jams/README.md, charts/proxy-traffic-jams/templates/NOTES.txt, charts/proxy-traffic-jams/templates/_helpers.tpl, charts/proxy-traffic-jams/templates/configmap.yaml, charts/proxy-traffic-jams/templates/deployment.yaml, charts/proxy-traffic-jams/templates/ingress.yaml, charts/proxy-traffic-jams/templates/pdb.yaml, charts/proxy-traffic-jams/templates/service.yaml, charts/proxy-traffic-jams/values.yaml
Add new chart: proxy-traffic-jams
=> Add chart proxy-traffic-jams

charts/tiles-api/Chart.yaml, charts/tiles-api/README.md, charts/tiles-api/README.md.gotmpl, charts/tiles-api/configs/config.yaml, charts/tiles-api/configs/importer/importer.yaml, charts/tiles-api/configs/importer/job.yaml, charts/tiles-api/templates/NOTES.txt, charts/tiles-api/templates/_helpers.tpl, charts/tiles-api/templates/api.configmap.yaml, charts/tiles-api/templates/deployment.yaml, charts/tiles-api/templates/hpa.yaml, charts/tiles-api/templates/import.configmap.yaml, charts/tiles-api/templates/ingress.yaml, charts/tiles-api/templates/job.yaml, charts/tiles-api/templates/pdb.yaml, charts/tiles-api/templates/role.yaml, charts/tiles-api/templates/rolebinding.yaml, charts/tiles-api/templates/secret.yaml, charts/tiles-api/templates/service.yaml, charts/tiles-api/templates/serviceaccount.yaml, charts/tiles-api/templates/vpa.yaml, charts/tiles-api/values.yaml
Глобальное переименование tileserver в tiles-api (чарт, параметры внутри конфигурации)
=> Переименование tileserver -> tiles-api

charts/gis-platform/Chart.yaml, charts/gis-platform/gis-platform-config/configuration/MapConfig.json
Чтобы не деплоить Нави сервисы в первом релизе.
=> remove availability area in evergis from release

charts/gis-platform/Chart.yaml, charts/gis-platform/gis-platform-config/configure.sh
Когда заводился новый пользователь, ему автоматом не шарились базовые слои, починил это автошарингом
=> fix sharing with base layers for new created user

charts/tiles-api/Chart.yaml, charts/tiles-api/templates/deployment.yaml
При каждом импорте данных (обновлении) создается новый тайлсет с уникальным идентификатором на основе выгрузки. Нужно чтобы происходил перезапуск подов в случае обновления этого идентификатора
=> Добавлен автоматический перезапуск подов в случае обновления манифеста

charts/catalog-api/Chart.yaml, charts/gis-platform/Chart.yaml, charts/gis-platform/values.yaml, charts/keys/Chart.yaml, charts/keys/values.yaml, charts/mapgl-js-api/Chart.yaml, charts/navi-back/Chart.yaml, charts/navi-castle/Chart.yaml, charts/navi-front/Chart.yaml, charts/navi-router/Chart.yaml, charts/proxy-traffic-jams/Chart.yaml, charts/search-api/Chart.yaml, charts/tiles-api/Chart.yaml
=> release 0.1.3

charts/catalog-api/Chart.yaml, charts/gis-platform/Chart.yaml, charts/gis-platform/values.yaml, charts/keys/Chart.yaml, charts/mapgl-js-api/Chart.yaml, charts/navi-back/Chart.yaml, charts/navi-castle/Chart.yaml, charts/navi-front/Chart.yaml, charts/navi-router/Chart.yaml, charts/proxy-traffic-jams/Chart.yaml, charts/search-api/Chart.yaml, charts/tiles-api/Chart.yaml
=> release 0.1.5

charts/catalog-api/Chart.yaml, charts/gis-platform/Chart.yaml, charts/gis-platform/values.yaml, charts/keys/Chart.yaml, charts/mapgl-js-api/Chart.yaml, charts/navi-back/Chart.yaml, charts/navi-castle/Chart.yaml, charts/navi-front/Chart.yaml, charts/navi-router/Chart.yaml, charts/proxy-traffic-jams/Chart.yaml, charts/search-api/Chart.yaml, charts/tiles-api/Chart.yaml, charts/tiles-api/values.yaml
=> release 0.1.6

charts/gis-platform/gis-platform-config/layer/2gis.json, charts/gis-platform/gis-platform-config/layer/2gis_traffic.json, charts/gis-platform/gis-platform-config/layer/satellite_imagery.json
Протащил все правки в конфигах слоев, что сделали и проверили на проде
=> update layers config

charts/navi-castle/templates/configmapbuilder.yaml
@Fullmetal8ender поддержка передачи имени файла манифеста в castle
=> Use dgctlstorage manifest values

charts/gis-platform/gis-platform-config/configuration/MapConfig.json
Добавил логотипы и `defaultPosition` со стейджинга
=> [gis-platform] Update MapConfig

Breaking-Changes.md, CHANGELOG.md, charts/catalog-api/Chart.yaml, charts/gis-platform/Chart.yaml, charts/keys/Chart.yaml, charts/mapgl-js-api/Chart.yaml, charts/navi-back/Chart.yaml, charts/navi-castle/Chart.yaml, charts/navi-front/Chart.yaml, charts/navi-router/Chart.yaml, charts/proxy-traffic-jams/Chart.yaml, charts/search-api/Chart.yaml, charts/tiles-api/Chart.yaml, charts/tiles-api/values.yaml
=> Release 1.0.4

CHANGELOG.md, charts/catalog-api/Chart.yaml, charts/gis-platform/Chart.yaml, charts/keys/Chart.yaml, charts/mapgl-js-api/Chart.yaml, charts/navi-back/Chart.yaml, charts/navi-castle/Chart.yaml, charts/navi-castle/values.yaml, charts/navi-front/Chart.yaml, charts/navi-front/values.yaml, charts/navi-router/Chart.yaml, charts/proxy-traffic-jams/Chart.yaml, charts/search-api/Chart.yaml, charts/tiles-api/Chart.yaml
=> Release 1.0.5

CHANGELOG.md, charts/bss-receiver/Chart.yaml, charts/bss-receiver/values.yaml, charts/catalog-api/Chart.yaml, charts/catalog-api/values.yaml, charts/gis-platform/Chart.yaml, charts/gis-platform/values.yaml, charts/keys/Chart.yaml, charts/mapgl-js-api/Chart.yaml, charts/navi-back/Chart.yaml, charts/navi-castle/Chart.yaml, charts/navi-front/Chart.yaml, charts/navi-router/Chart.yaml, charts/proxy-traffic-jams/Chart.yaml, charts/proxy-traffic-jams/values.yaml, charts/search-api/Chart.yaml, charts/search-api/values.yaml, charts/tiles-api/Chart.yaml, image_versions.txt
* catalog-api
* search-api
* gis-platform
* bss-receiver
=> Release 1.0.8

CHANGELOG.md, charts/bss-receiver/Chart.yaml, charts/catalog-api/Chart.yaml, charts/gis-platform/Chart.yaml, charts/gis-platform/values.yaml, charts/keys/Chart.yaml, charts/mapgl-js-api/Chart.yaml, charts/navi-back/Chart.yaml, charts/navi-castle/Chart.yaml, charts/navi-front/Chart.yaml, charts/navi-router/Chart.yaml, charts/proxy-traffic-jams/Chart.yaml, charts/search-api/Chart.yaml, charts/tiles-api/Chart.yaml, image_versions.txt
=> Release 1.0.9

charts/tiles-api/README.md, charts/tiles-api/configs/importer/importer.yaml, charts/tiles-api/values.yaml
Добавлен параметр cassandraHostsClockTimeCheckLimit
=> [tiles-api] Add cassandraHostsClockTimeCheckLimit param

charts/tiles-api/README.md, charts/tiles-api/configs/importer/importer.yaml, charts/tiles-api/values.yaml
This reverts commit 47a994687a79034c8aa07a38cc240530214cb64d.
=> Revert "Add cassandraHostsClockTimeCheckLimit param (#99)"

charts/navi-restrictions/README.md
valid links available at https://docs.2gis.com/en/on-premise
README updated accordingly
=> [navi-restrictions] external docs links updated

charts/navi-router/README.md, charts/navi-router/values.yaml
Вдогонку к PR https://github.com/2gis/on-premise-helm-charts/pull/125, по результатам обсуждений в PR https://github.com/2gis/digital-docs/pull/324.
=> SH #311: Fixed list of settings in the `router` section.

charts/catalog-api/templates/NOTES.txt, charts/gis-platform/templates/NOTES.txt, charts/keys/templates/NOTES.txt, charts/mapgl-js-api/templates/NOTES.txt, charts/navi-async-matrix/templates/NOTES.txt, charts/navi-restrictions/templates/NOTES.txt, charts/stat-receiver/templates/NOTES.txt, charts/tiles-api/templates/NOTES.txt, charts/traffic-proxy/templates/NOTES.txt
В выводе будет на подобии
```
NOTES:
Search api service is released as "dmm-search-api" service at "devops-on-premise" namespace.
You can check service using curl
https://dmm-search-api.on-premise.2gis.dev/v2/status
```
=> Add ingress url to NOTES.txt

charts/keys/templates/migrate/job.yaml
Reverts 2gis/on-premise-helm-charts#168
=> Revert "WIP: Use migrate subcommand from keysctl tool for db migrations"

charts/pro-ui/README.md, charts/pro-ui/templates/_helpers.tpl, charts/pro-ui/values.yaml
В новом релизе при отсутствии переменных окружения, UI Прошки будет загружать статику стилей со своего сервера
=> PRO-1793: mk style envs optional

CHANGELOG.md, charts/catalog-api/Chart.yaml, charts/gis-platform/Chart.yaml, charts/keys/Chart.yaml, charts/license/Chart.yaml, charts/mapgl-js-api/Chart.yaml, charts/navi-async-matrix/Chart.yaml, charts/navi-back/Chart.yaml, charts/navi-castle/Chart.yaml, charts/navi-front/Chart.yaml, charts/navi-restrictions/Chart.yaml, charts/navi-router/Chart.yaml, charts/pro-api/Chart.yaml, charts/pro-api/values.yaml, charts/pro-ui/Chart.yaml, charts/pro-ui/values.yaml, charts/search-api/Chart.yaml, charts/stat-receiver/Chart.yaml, charts/tiles-api/Chart.yaml, charts/traffic-proxy/Chart.yaml, image_versions.txt
=> release 1.5.6

charts/navi-front/templates/_helpers.tpl, charts/navi-splitter/Chart.yaml, charts/navi-splitter/README.md, charts/navi-splitter/templates/NOTES.txt, charts/navi-splitter/templates/_helpers.tpl, charts/navi-splitter/templates/deployment.yaml, charts/navi-splitter/templates/hpa.yaml, charts/navi-splitter/templates/ingress.yaml, charts/navi-splitter/templates/service.yaml, charts/navi-splitter/templates/serviceaccount.yaml, charts/navi-splitter/templates/tests/test-connection.yaml, charts/navi-splitter/values.yaml
Чарт navi-splitter с поддержкой CTX DM запросов
=> Init splitter chart

charts/tiles-api/configs/api.yaml, charts/tiles-api/values.yaml
Документацию в комментарии не добавлял, так как этот параметр только для нас.
=> Добавлен фичерубильник для лицензий

charts/search-api/README.md, charts/search-api/templates/deployment.yaml, charts/search-api/values.yaml
Начнет работать только с 7.62.1-s3ssl или старше
=> [SEARCH] s3 ssl for search-api

charts/tiles-api/configs/api.yaml, charts/tiles-api/configs/importer/importer.yaml, charts/tiles-api/configs/importer/job.yaml, charts/tiles-api/templates/api.secret.yaml, charts/tiles-api/templates/cassandra-cleaner-job.yaml, charts/tiles-api/templates/deployment.yaml, charts/tiles-api/templates/import.secret.yaml, charts/tiles-api/templates/job.yaml, charts/tiles-api/templates/secret.yaml
необходимая версия tiles - 4.48.2
=> IODEV-1546 cassandra credentials moved to secret

charts/navi-router/Chart.yaml, charts/navi-router/README.md, charts/navi-router/values.yaml
Новая версия navi-router: 6.16.0
=> Navi router new tag

charts/navi-front/Chart.yaml, charts/navi-front/README.md, charts/navi-front/templates/configmap-base.yaml, charts/navi-front/values.yaml
Обновление образа до версии `1.24.1`
Обновление обработки 4хх кодов ответа (с поддержкой в роутере `6.16.0`)
Обновление `templates/configmap-base.yaml` часть locations переработано.
=> Update chart navi-front

charts/navi-async-grpc-proxy/values.yaml
Version 1.0.0 - bundling python code
=> New tag for navi-async-grpc-proxy

charts/pro-ui/README.md, charts/pro-ui/templates/ui/deployment.yaml, charts/pro-ui/values.schema.json, charts/pro-ui/values.yaml
=> Revert: healthcheck pro-ui

CHANGELOG.md
Added known release dates from the [document](https://docs.2gis.com/ru/on-premise/releases/on-premise)
=> Добавить дату релиза в CHANGELOG.md

.github/workflows/lint.yaml, .github/workflows/release.yaml
Increase versions of 
actions/checkout@v4
helm/chart-testing-action@v2.5.0
=> GitHub actions node version warning

charts/navi-front/templates/configmap-base.yaml
Adds support for /routing/7.0.0
=> Support for routing/7.0.0

.github/workflows/lint.yaml
Update version to helm/chart-testing-action@v2.6.0
=> GitHub Actions: Update lint.yaml

charts/pro-api/templates/user-asset-importer.yaml, charts/pro-api/values.yaml, charts/pro-ui/values.yaml
UI:
- обновили NodeJS до 20 https://jira.2gis.ru/browse/PRO-2855
- Новая фича по добавлению и удалению пользовательских объектов в юзер-ассетах. Проверить можно перейдя в юзер-ассет, выбрать территорию и нажать Add object. Удаление доступно, если перейти в карточку юзер-ассета. https://jira.2gis.ru/browse/PRO-3247
- Исправили сценарий редактирования слоя с выборкой, когда добавляем новые айтемы https://jira.2gis.ru/browse/PRO-3690
API:
- Метод PUT /asset/filters поддерживает обновление фильтров любых пользовательских ассетов https://jira.2gis.ru/browse/PRO-3685
- Возвращается 2хх ответ при отмене запроса с клиента https://jira.2gis.ru/browse/PRO-3729
- Исправлен критичный баг с проверкой прав https://jira.2gis.ru/browse/PRO-3845
-В методе создания ассета можно передавать опциональный …
=> [PRO-3879]: updated UI to 1.3.0; API to 1.1.60

.github/workflows/lint.yaml
add linter run for develop branch
=> On-premise Feature: add lint for develop

Breaking-Changes.md, CHANGELOG.md
Update breaking changes for release 1.14.0
=> Release 1.14.0 update: breaking changes

charts/catalog-api/README.md, charts/catalog-api/values.yaml
Catalog-api fix doc. Support only  license v1
=> [ONPREM-604] Catalog-api fix doc. Support only  license v1

charts/citylens/templates/api/configmap.yaml, charts/citylens/templates/api/deployment.yaml, charts/citylens/templates/web/deployment.yaml, charts/citylens/values.yaml
Changelog:
* citylens-api:
* fix verify_ssl option rendering in configmap
* fix Deployment nodeSelector, affinity & tolerations
* citylnes-web:
* update Pro integration (fields order & etc)
* fix Deployment nodeSelector, affinity & tolerations
=> Fix citylens-api configmap & update Citylens to 1.3.2

charts/keycloak/README.md
Поправили ссылку на документацию
=> Keycloak - fix readme

charts/keys/Chart.yaml, charts/keys/values.yaml
Импорт сервисов Map Matching API и Truck Direction API в On-Premise
=> [keys-api] up keys-backend. Support truck, map-matching api keys

charts/citylens/templates/web/configmap.yaml, charts/citylens/templates/web/deployment.yaml, charts/citylens/values.yaml
Changelog:
* citylens-api: stricter validation
* citylens-web: new track page UI, configurable track reload timeout
=> Update citylens to 1.4.0

.github/CODEOWNERS
add codeowners file for auto add reviwers
=> Feature: add codeowners file

charts/navi-restrictions/Chart.yaml, charts/navi-restrictions/README.md, charts/navi-restrictions/values.yaml
Bugfix release. Reduced hardcode
=> navi-restrictions-api 1.0.1 release

charts/generic-chart/.helmignore, charts/generic-chart/Chart.yaml, charts/generic-chart/README.md, charts/generic-chart/templates/_deployment.yaml, charts/generic-chart/templates/_helpers.tpl, charts/generic-chart/templates/_hpa.yaml, charts/generic-chart/templates/_pdb.yaml, charts/generic-chart/templates/_service.yaml, charts/generic-chart/templates/_serviceaccount.yaml, charts/generic-chart/templates/_vpa.yaml, charts/generic-chart/values.yaml
Charts occasionally transitioning to generic library one.
Not used at the moment.
=> generic-chart added

charts/pro-ui/Chart.yaml, charts/pro-ui/README.md, charts/pro-ui/values.yaml
Changelog:  https://tsup.2gis.dev/pro/pro-ui/changelog/1.7.6..1.9.0
pro api – [тут](https://github.com/2gis/on-premise-helm-charts/pull/394). Текущая версия тестировалась с API 1.4.0
1. Нужны дать юзеру права `quantity	isochrone_op	1000`
2. Создать слой в котором до 500 айтемов
3. Создать зоны доступности (`Proximity zones` кнопка)
4. Перейти в созданный злой с зонами доступностями
ОР: в этом слое есть кнопка Aggregate data
5. Задать имя, выбрать атрибуты и нажать Create
ОР: создался слой
Больше проверок [тут](https://confluence.2gis.ru/pages/viewpage.action?pageId=435207001#id-Списокпроверокдлярелиза-Агрегацияпополигонам), но мне кажется этого достаточно будет
Тут просто проверить, что ссылки отсутствуют. Они были снизу справа и в поповере при нажатии на профиль
1. Открываем …
=> PRO-3609: upgrade pro ui to 1.9.0

.github/pull_request_template.md
add PR template
https://docs.github.com/en/enterprise-server@3.8/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository
=> Feature: add PR template

charts/pro-api/Chart.yaml, charts/pro-api/README.md, charts/pro-api/values.yaml
Изменения: https://tsup.2gis.dev/pro/pro-api/1.6.0
___
- Добавлена авторизация в контроллере Proxy (только для PUT/POST запросов) – https://jira.2gis.ru/browse/PRO-4355
1. `asset	momrah_pollution	    read` – должна быть такая пермиссия у акка
2. Перейти в ассент Frames
3. Найти новые треки на карте
4. Открыть карточку
5. Открыть фото
6. Клик по кнопкам модерации (`Everything is correct`\\`Report an error`)
ОР: отсутствуют ошибки, есть нотификация, что всё успешно, спустя время у карточка будет помечена как отмодерированная
___
- Добавить арабские переводы для описания системных аcсетов – https://jira.2gis.ru/browse/PRO-4495
На дашборде (`/library`) и при открытии ассета, описание и название ассета на арабском языке
=> PRO-4774: upgraded PRO API to 1.6.0

.github/pull_request_template.md
Чек-лист на русском, т,к. styleguide тоже на русском.
=> Чек-лист код-ревью для описания PR

Breaking-Changes.md, CHANGELOG.md
=> fix Breaking-Changes.md and CHANGELOG.md

charts/pro-api/values.yaml
=> fix pro-api/values.yaml doc

charts/pro-ui/templates/ui/styles-import-starter.yaml
- Изменены хуки для импортера стилей. Теперь импорт стилей запускается на pre-install, pre-upgrade
- `PRO-5009` https://jira.2gis.ru/browse/PRO-5009
- Отсутствуют
=> [PRO-5009] Изменены хуки для импортера стилей.

charts/pro-ui/templates/_helpers.tpl, charts/pro-ui/templates/ui/role.yaml, charts/pro-ui/templates/ui/rolebinding.yaml, charts/pro-ui/templates/ui/secrets-styles-importer.yaml, charts/pro-ui/templates/ui/service-account.yaml, charts/pro-ui/templates/ui/styles-import-starter.yaml
=> [PRO-UI] fix helm-hooks

charts/citylens/templates/web/configmap.yaml
- add missing predictions topic
=> Fix citylens-web configmap: add missing predictions topic

.github/scripts/check-readme.sh, charts/gis-platform/README.md, charts/gis-platform/values.yaml
- Gis-platform. Мелкие правки по дефолтным параметрам
=> Gis-platform. Мелкие правки по дефолтным параметрам

charts/license/templates/statefulset.yaml
- Добавили в спек пода обязательное монтирование директории с сертификатом k8s.
- [IODEV-2070](https://jira.2gis.ru/browse/IODEV-2070)
=> [license] Fixed issue with k8s ca automount

Breaking-Changes.md, charts/citylens/Chart.yaml, charts/citylens/README.md, charts/citylens/templates/web/configmap.yaml, charts/citylens/values.yaml
- Better logging at track init endpoint
- Updated integration with CamCom (`FR 13.05.24`)
- `FR 13.05.24`
- See [Breaking-Changes](../Breaking-Changes.md)
=> Bump citylens to 1.10.0

charts/keys/Chart.yaml, charts/keys/README.md, charts/keys/templates/helpers.tpl, charts/keys/templates/secret-deploys.yaml, charts/keys/values.yaml, image_versions.txt
https://tsup.2gis.dev/pro/keys-admin/0.8.0
https://docker-hub.2gis.ru/harbor/projects/163/repositories/keys-ui/artifacts-tab – образ залили
- https://jira.2gis.ru/browse/PRO-5559
=> PRO-5559: upgrade key ui to latest

charts/search-api/README.md, charts/search-api/values.yaml
=> Проверить ПР search 478. Fix readme

charts/citylens/Chart.yaml, charts/citylens/README.md, charts/citylens/templates/api/configmap.yaml, charts/citylens/values.yaml
- citylens-api
- Removed POST /api/1.0/callbacks/camcom endpoint as not used & deprecated
- Added POST /api/1.0/routes/{track_uuid}/frame endpoint for new mobile app
- citylens-web
- Better UI on frames list page
=> Citylens 1.12.0

charts/navi-back/README.md, charts/navi-back/templates/configmap.yaml, charts/navi-back/templates/secret.yaml, charts/navi-back/values.yaml
- Logs field name parameterized, `msg` renamed to `custom.navi_msg` by default
n/a
=> [chart/navi-back] chart syncup

styleguide.md
- Добавил styleguide kafka example
- Удалил невалидную ссылку
=> Chore: styleguide kafka example

charts/navi-front/templates/configmap-base.yaml
- Добавить /bicycle в mfront
- https://jira.2gis.ru/browse/DEVOPS-1348
=> DEVOPS-1348: add bicycle nginx location to navi-front

charts/platform/Chart.yaml, charts/platform/README.md, charts/platform/values.yaml, image_versions.txt
https://tsup.2gis.dev/gefest/gefest/0.15.1
- Метод “/import” АПИ стилей переделан на multipart (https://jira.2gis.ru/browse/GEFEST-1026)
=> Upgrade version of platform UI to 0.15.1

charts/navi-castle/README.md, charts/navi-castle/values.yaml
- Поправил описание values
- DEVOPS-1394
=> [DEVOPS-1394] fix typo in castle chart

charts/navi-castle/templates/statefulset.yaml
- fixed securityContext
- [`Issue-123` (Link to related issue)](https://jira.2gis.ru/browse/DEVOPS-1409)
=> DEVOPS-1409: add securityContext

.github/workflows/mm-pr-notify.yaml, .github/workflows/mm-release-notify.yaml
- Добавлено оповещение в ММ при создании релизного тега;
- Джоба дожидается успешного выполнения workflow "Release Charts";
- Переименовано название файла workflow PR-нотификаций & правки по code-style.
- `ONPREM-932` 
=> Add github action "MM Release notification"

charts/gis-platform/templates/gis-platform-portal-configmap.yaml, charts/gis-platform/templates/gis-platform-portal-dep.yaml
- Switch to static nginx config
N/A
N/A
=> [gis-platform] Do not use config template

styleguide.md
- Update styleguide for logging block
=> Chore: Update styleguide for logging block

charts/citylens/Chart.yaml, charts/citylens/README.md, charts/citylens/templates/web/configmap.yaml, charts/citylens/values.yaml
- Better & stricter image EXIF validation at endpoints `POST /api/1.0/routes/{track_uuid}/frames` and `POST /api/1.0/routes/{track_uuid}/frame`
- Enabled licence checking at endpoints `/routes-api/...`
- citylens-frames-saver:
- Fixed possible crash when processing image EXIF
- New 'App version' field on frame card in "Frames" asset in Pro
Data version changed, now required version is 5
=> Citylens 1.14.0

charts/traffic-proxy/values.yaml
- Fix lint warning for accessLog value
=> [traffic-proxy] Fix lint warning for accessLog value

.github/workflows/mm-release-notify.yaml
- Правка вызова тега $github.ref_name -> $github.event.workflow_run.head_branch
=> Fix release MM notification 

charts/citylens/Chart.yaml, charts/citylens/README.md, charts/citylens/templates/helpers.tpl, charts/citylens/templates/web/configmap.yaml, charts/citylens/values.yaml
- citylens-api
- Improved stability of endpoint POST /api/1.0/routes/{track_uuid}/frame (addressed crashes with exif_processing_error)
=> Citylens 1.15.0

charts/license/Chart.yaml, charts/license/README.md, charts/license/values.yaml
- Починили панику при некоторых запросах по отсутствующему сервису.
=> [license] Upgraded version to 2.2.4

charts/mapgl-js-api/Chart.yaml, charts/mapgl-js-api/README.md, charts/mapgl-js-api/values.yaml
- [releases](https://docs.2gis.com/en/mapgl/releases)
=> TILES-7091 update actual version

charts/search-api/README.md, charts/search-api/values.yaml
- Update nginx version 1.21.6 -> 1.25.4
- https://jira.2gis.ru/browse/ONPREM-1274
- n/a
=> [search-api] Update nginx version 1.21.6 -> 1.25.4

charts/floors-api/README.md, charts/floors-api/values.yaml
- Update nginx version 1.21.6 -> 1.25.4
- https://jira.2gis.ru/browse/ONPREM-1274
- n/a
=> [floors-api] Update nginx version 1.21.6 -> 1.25.4

Breaking-Changes.md, charts/floors-api/README.md, charts/floors-api/templates/deployment.yaml, charts/floors-api/values.yaml, charts/mapgl-js-api/README.md, charts/mapgl-js-api/templates/deployment.yaml, charts/mapgl-js-api/values.yaml, charts/search-api/README.md, charts/search-api/templates/deployment.yaml, charts/search-api/values.yaml, charts/traffic-proxy/README.md, charts/traffic-proxy/templates/deployment.yaml, charts/traffic-proxy/values.yaml
Изменения:
- Добавлен параметр `enableServiceLinks`
- Добавлен в `values` и описание параметра  `terminationGracePeriodSeconds`
- [ONPREM-1374](https://jira.2gis.ru/browse/ONPREM-1374)
- If there are breaking changes, they need to be added to the file [Breaking-Changes](https://github.com/2gis/on-premise-helm-charts/blob/ONPREM-1374-enableServiceLinks/Breaking-Changes.md)
=> ONPREM-1374[mapgl, floors, traffic-proxy, search] Добавление параметров enableServiceLinks, terminationGracePeriodSeconds

charts/traffic-proxy/README.md, charts/traffic-proxy/values.yaml
- Update nginx version 1.21.6 -> 1.25.4
- https://jira.2gis.ru/browse/ONPREM-1274
- n/a
=> [traffic-proxy] Update nginx version 1.21.6 -> 1.25.4

charts/mapgl-js-api/Chart.yaml, charts/mapgl-js-api/README.md, charts/mapgl-js-api/values.yaml
- [releases](https://docs.2gis.com/en/mapgl/releases) 
=> TILES-7086 Updated mapgl-api appVersion

charts/navi-castle/README.md, charts/navi-castle/values.yaml
- Update nginx version 1.21.6 -> 1.25.4
- https://jira.2gis.ru/browse/ONPREM-1274
- n/a
=> [navi-castle] Update nginx version 1.21.6 -> 1.25.4

charts/navi-front/Chart.yaml, charts/navi-front/README.md, charts/navi-front/values.yaml
- Underlying `nginx` upgraded to 1.25.4
- n/a
- n/a
=> navi-front upd 1.24.1 -> 1.25.2

charts/pro-api/README.md, charts/pro-api/templates/_helpers.tpl, charts/pro-api/templates/secrets.yaml, charts/pro-api/values.yaml
Изменения:
- $postgres.api.ro null -> []
- $postgres.tasks.ro null -> []
- Не подключать настройки postgres.tasks, при условии, если tasks.settings.enabled = false
=> [PRO-API] Add for skip ".Values.postgres.tasks"

.github/workflows/release-oci.yaml
=> Доработать GH Actions на публикацию чартов в GH OCI

.github/workflows/release-oci.yaml
- `ONPREM-1388` (Link to related issue)
=> Исправление описания workflow release-oci

.github/workflows/release-oci.yaml
- `ONPREM-1388` (Link to related issue)
=> Изменяем имя workflow run для release-oci

charts/license/templates/secret.yaml
- поправила ошибку деплоя сервиса лицензии
=> Fix license service deploy

charts/generic-chart/README.md, charts/generic-chart/templates/_cronjob.yaml, charts/generic-chart/templates/_helpers.tpl, charts/generic-chart/templates/_job_spec.yaml, charts/generic-chart/templates/_networkpolicy.yaml, charts/generic-chart/templates/_service.yaml, charts/generic-chart/templates/_vpa.yaml, charts/generic-chart/values.yaml
- more parameters support: activeDeadlineSeconds (jobs), externalTafficPolicy (service), controlledValues (vpa)
- more templates: networkPolicy
- resource quantity helper to cast resource units
- minor template fixes
- n/a
- n/a
=> navi generic chart 0.0.22 release

charts/navi-router/Chart.yaml, charts/navi-router/README.md, charts/navi-router/values.yaml
- https://tsup.2gis.dev/navi/router/6.28.0
- n/a
- n/a
=> navi router 6.28.0.3 release

charts/catalog-api/README.md, charts/catalog-api/values.yaml
=> Обновлены версии Catalog APIs

charts/keys/templates/import/job.yaml
- Убрал флаг дата-миграции из джобы импорта
- [`GEFEST-1454`](https://jira.2gis.ru/browse/GEFEST-1454)
=> GEFEST-1454 Убрал флаг дата-миграции из джобы чарта Keys

charts/mapgl-js-api/Chart.yaml, charts/mapgl-js-api/README.md, charts/mapgl-js-api/values.yaml
- [releases](https://docs.2gis.com/en/mapgl/releases)
=> Updated mapgl-api version to v1.56.0

charts/keys/README.md, charts/keys/values.yaml
https://tsup.2gis.dev/gefest/keys-admin/changelog/0.10.3..0.10.5
В образах keys-ui используется node v22.
https://jira.2gis.ru/browse/GEFEST-1512
=> GEFEST-1512 keys ui release 0.10.5

Breaking-Changes.md, charts/citylens/README.md, charts/citylens/templates/api/configmap.yaml, charts/citylens/values.yaml
- Support for displaing driver info from OIDC provider at citylens-web, Pro assets "Frames", "Drivers" (`.Values.api.auth.storeOIDCUserinfoFields`)
- Urbi CR002
- see [Breaking-Changes](../Breaking-Changes.md)
=> Bump citylens to 1.17.5

charts/citylens-routes-ui/.gitignore, charts/citylens-routes-ui/.helmignore, charts/citylens-routes-ui/Chart.yaml, charts/citylens-routes-ui/README.md, charts/citylens-routes-ui/templates/NOTES.txt, charts/citylens-routes-ui/templates/_helpers.tpl, charts/citylens-routes-ui/templates/configmap.yaml, charts/citylens-routes-ui/templates/deployment.yaml, charts/citylens-routes-ui/templates/hpa.yaml, charts/citylens-routes-ui/templates/ingress.yaml, charts/citylens-routes-ui/templates/pdb.yaml, charts/citylens-routes-ui/templates/secrets.yaml, charts/citylens-routes-ui/templates/service.yaml, charts/citylens-routes-ui/templates/vpa.yaml, charts/citylens-routes-ui/values.yaml
=> [CITYLENS-728] Add citylens-routes-ui chart

charts/pro-ui/README.md, charts/pro-ui/templates/_env.tpl, charts/pro-ui/values.schema.json, charts/pro-ui/values.yaml
- Добавил пропущенную секцию zenith. Указал для неё параметры и их описание.
- Сделал в рамках «быстро-фикса».
- Ломающих изменений нет.
=> Добавлена пропущенная секция Zenith для чарта pro-ui.

charts/pro-api/templates/asset-importer.yaml
- Change AssetImporter DB connection parameter from pro-tasks to pro-api
=> [Pro-api] Fix AssteImporter db connection param

charts/tilegen-api/Chart.yaml
=> [Tilegen-API]  Правка имени чарта

charts/mapgl-js-api/Chart.yaml, charts/mapgl-js-api/README.md, charts/mapgl-js-api/values.yaml
- [releases](https://docs.2gis.com/en/mapgl/releases)
=> TILES-7274 new mapgl-api v1.57.0

charts/citylens/README.md, charts/citylens/templates/routes-migrations/migration.yaml, charts/citylens/templates/routes-worker/deployment.yaml, charts/citylens/values.yaml
- `Bugfix proxy to Navi`
- `Bugfix calculate amana coverage`
- `Set routes.worker.busConfig.consumers.appEvents.groupId **Requiered**`
- `CITYLENS-1111` 
- `CITYLENS-1121`
=> citylens-routes-api update images

charts/citylens-routes-ui/Chart.yaml, charts/citylens-routes-ui/README.md, charts/citylens-routes-ui/values.yaml
=> [CITYLENS-1217] Add PKCE support for OIDC auth

charts/navi-router/values.yaml
=> Hotfix Navi-router: add routing-api token

styleguide.md
add more examples to styleguide for kafka, postgreSQL
- no
=> Chore: add more examples to styleguide

.github/workflows/lint-helm-charts.yaml, .github/workflows/lint-helm-charts.yml
=> Настроить линтеры на helm chart-ы. Fix chart-testing

.github/workflows/mm-release-notify.yaml
- The MM notification now includes the date of the next scheduled release
- ONPREM-1449
=> [ONPREM-1449] next release date notify

charts/catalog-api/templates/api/deployment.yaml, charts/citylens/templates/api/deployment.yaml, charts/floors-api/templates/deployment.yaml, charts/keys/templates/api/deployment.yaml, charts/navi-castle/templates/statefulset.yaml, charts/pro-api/templates/deployment.yaml, charts/pro-ui/templates/ui/deployment.yaml, charts/search-api/templates/_helpers.tpl, charts/search-api/templates/configmap.yaml, charts/search-api/templates/deployment.yaml, charts/search-api/templates/hpa.yaml, charts/search-api/templates/ingress.yaml, charts/search-api/templates/pdb.yaml, charts/search-api/templates/secret.yaml, charts/search-api/templates/service.yaml, charts/tiles-api/templates/deployment.yaml, charts/twins-api/templates/api/deployment.yaml, styleguide.md
=> [ONPREM-1574] Search chart update

charts/citylens-routes-ui/templates/deployment.yaml
=> [Citylens-routes-ui] Fix mapgl url

charts/search-api/README.md, charts/search-api/values.yaml
=> [Search-api] bump to 7.90.0

charts/navi-castle/templates/cronjob.yaml
- `Fix of navi-castle values.tolerations context using` 
- `ONPREM-1624`
=> [ONPREM-1624] - Update navi-castle values tolerations context

charts/twins-api/README.md, charts/twins-api/values.yaml
- Зафиксировал новую версию twins api
- `WAPI-23888` (https://jira.2gis.ru/browse/WAPI-23888)
=> релиз twins api 1.18.0

.github/workflows/lint-helm-charts.yaml, charts/gis-platform/Chart.yaml
=> Настроить линтеры на helm chart-ы. Build dependencies

.github/workflows/release.yaml
* Fix GH Action release helm
* fix update index action
---------
=> Fix Release action (#650)

.github/workflows/mm-release-notify.yaml
=> [fix] release MM notrify

charts/tiles-api/README.md, charts/tiles-api/configs/proxy.yaml, charts/tiles-api/values.yaml
Reverts 2gis/on-premise-helm-charts#642
=> Revert "BASIS-244: Добавлено разделение токенов аутентификации для растра"

charts/catalog-api/README.md, charts/catalog-api/values.yaml
=> Обновлены версии catalog-api 3.647.0 и catalog-importer 1.12.1

Breaking-Changes.md
=> ONPREM-1666 [1.38.0] Breaking-Changes update

charts/keys/README.md, charts/keys/values.yaml, image_versions.txt
- https://tsup.2gis.dev/gefest/keys-admin/0.10.6
=> GEFEST-0: up version keys ui to 0.10.6

charts/navi-castle/README.md, charts/navi-castle/templates/configmapnginx.yaml, charts/navi-castle/templates/cronjob.yaml, charts/navi-castle/templates/secret-extra-env.yaml, charts/navi-castle/templates/statefulset.yaml, charts/navi-castle/values.yaml
- `enableServiceLinks` is off by default
- new parameters for specific test usage: `initContainers`, `extraVolumes`, `extraVolumeMounts`, `extraEnvVarsSecret`
- default locations might be overridden with `nginx.locationsBlock`
- n/a
- n/a
=> [chart/navi-castle] chart upstream syncup

charts/pro-ui/Chart.yaml, charts/pro-ui/README.md, charts/pro-ui/templates/_env.tpl, charts/pro-ui/values.yaml
* **Работа с несколькими сценами:**
* Доступна новая функциональность работы с несколькими сценами в рамках дэшборда.
* **Виджет "Временная шкала":**
* Добавлена возможность выбора шага "месяц" и "год".
* Выполнен редизайн настроек и добавлено сохранение состояния в роутинг.
* Добавлен график для количественного анализа объектов по времени.
* **Интерфейс дэшборда:**
* Выполнен редизайн тулбара для увеличения свободного пространства.
* Добавлен раздел на главной странице со списком из 3 последних открытых дашбордов.
* Добавлена возможность закрытия всех всплывающих окон перед показом следующего.
* **Слои и визуализация:**
* Добавлены подписи для слоя кластеров.
* Добавлены новые типы шкал для легенды ("Настраиваемая", "Экспоненциальная") и возможность ручной настройки диапазонов.
* …
=> [PRO-7982] update pro ui

.github/workflows/release-by-product.yaml, .github/workflows/release.yaml
Reverts 2gis/on-premise-helm-charts#682
=> Revert "wf by product"

charts/mapgl-js-api/Chart.yaml, charts/mapgl-js-api/README.md, charts/mapgl-js-api/values.yaml
See release notes from
version [v1.59.0](https://docs.2gis.com/en/mapgl/releases#nav-lvl1--v1.59.0)
version [v1.60.0](https://docs.2gis.com/en/mapgl/releases#nav-lvl1--v1.60.0)
of MapGL JS API
None
=> mapgl-api-v1.60.0

charts/pro-ui/README.md, charts/pro-ui/values.yaml
- Добавлена новая версия релиза Pro-UI 4.16.0
Глобальная фича:
- Добавлена возможность переключать UI на темную тему
- В url приложения добавлен GET-параметр lang, который показывает какой язык сейчас включен. Через этот параметр можно также поменять язык приложения.
Тултип и карточка объекта:
- Добавлена поддержка отображения только даты (без времени) для поля типа date в тултипе и карточке объекта.
Выдача по пользовательскому ассету:
- Разрешаем редактировать список объектов после удаления последнего элемента в пользовательском ассете.
Дашборд:
- Добавлена возможность выбирать сцену для добавления нового слоя при наличии у пользователя единственного дашборда
- починили перелеты в шареном дашборде
- Всплывающие подсказки при настройке слоя больше не блокируют пролистывание
Виджеты:
- …
=> [PRO-8197]

charts/navi-attractor/README.md, charts/navi-attractor/templates/_helpers.tpl, charts/navi-attractor/templates/configmap.yaml, charts/navi-attractor/templates/deployment.yaml, charts/navi-attractor/values.yaml
- TZ -> UTC
- support motorcycle and emergency routing
- custom filename for rtr
- up version to 7.39.1.9
- [DEVOPS-1785](https://jira.2gis.ru/browse/DEVOPS-1785)
=> [chart/navi-attractor] chart syncup

charts/citylens/Chart.yaml, charts/citylens/README.md, charts/citylens/templates/web/configmap.yaml, charts/citylens/templates/web/jobs/predictors-sync-job.yaml, charts/citylens/templates/web/jobs/pro-filters-update-job.yaml, charts/citylens/templates/workers/configmap.yaml, charts/citylens/templates/workers/deployment-dashboard-batch-events.yaml, charts/citylens/values.yaml
- citylens-api: removed restrictions proxying request to Routes Planner API via `/routes-api/*` endpoint: now all requests will be proxied to Routes Planner API if `.Values.api.routesApiBaseUrl` is set.
- citylens-web: track map matching: fixed cause of "Invalid delay between points" errors
- `CV-143`
- `CV-19`
- None
=> Citylens 1.18.3

.github/workflows/check-readme.yaml
- Версия node обновлена до 22 + откат версии readme-generator-for-helm до 2.7.0
-  https://jira.2gis.ru/browse/ONPREM-2035
=> Fix readme-generator

charts/citylens/templates/web/configmap.yaml
- Fix charts/citylens/templates/web/configmap.yaml rendering
=> Fix citylens/templates/web/configmap.yaml generation

charts/citylens-routes-ui/README.md, charts/citylens-routes-ui/values.yaml
Добавлен компонент слайдера
Добавлена подстановка ЕТД в редактор полигонов на экране задачи
Добавлена фильтрация полигонов по проектам
исправлено автообновление списка задач после добавления/редактирования задачи
Добавлены лоадеры на страницы территорий и проектов
Добавлены фильтры для исключения междугородных и федеральных дорог
Отображение полигонов при любом зуме
исправлена верстка длинных названий проектов
исправлено создание новой задачи сразу после создания предыдущей
=> Update citylens-routes-ui to version 1.3.0

charts/citylens-routes-ui/Chart.yaml, charts/citylens-routes-ui/README.md, charts/citylens-routes-ui/values.yaml
=> Update citylens-routes-ui to version 1.3.2

.github/workflows/build-data-updater.yaml
- Для сборки data-updater теперь используется Dockerfile из ветки develop
=> Use dockerfile from develop branch

.github/workflows/build-data-updater.yaml
=> Add develop branch checkout

charts/navi-back/README.md, charts/navi-back/values.yaml
=> [charts/navi-back] up version

charts/navi-splitter/Chart.yaml, charts/navi-splitter/README.md, charts/navi-splitter/values.yaml
- Обновлена версия образа до актуальной
- `DEVOPS-2121`
=> [navi-splitter] |DEVOPS-2121 | Up image version

charts/navi-async-matrix/README.md, charts/navi-async-matrix/values.yaml
- Добавлены возможные значения в описание типов топиков
- https://jira.2gis.ru/browse/ONPREM-2034
=> [navi-async-matrix] Add possible topic type

charts/navi-async-matrix/Chart.yaml, charts/navi-async-matrix/README.md, charts/navi-async-matrix/values.yaml
- Обновлены версии async-matrix & async-merger-matrix до актуальных
- `DEVOPS-2121`
=> [navi-async-matrix] | DEVOPS-2121 | up image versions

charts/navi-vrp-solver/Chart.yaml, charts/navi-vrp-solver/README.md, charts/navi-vrp-solver/values.yaml, charts/navi-vrp-task-manager/Chart.yaml, charts/navi-vrp-task-manager/README.md, charts/navi-vrp-task-manager/values.yaml
- Обновление версий vrp-solver & vrp-task-manager до актуальных
- `DEVOPS-2121`
=> [vrp-solver & vrp-task-manager] |DEVOPS-2121| up image versions
