charts/navi-back/templates/_helpers.tpl, charts/navi-back/templates/configmap.yaml, charts/navi-router/templates/_helpers.tpl, charts/navi-router/templates/configmap.yaml
@Fullmetal8ender @dekhtyarev   
Теперь можно подключать правила для navi-back и navi-router как value:
```
rules: 
[ 
{
"name": "dammam_cr",
"router_projects": [
"dammam"
],
"moses_projects": [
"dammam"
],
"projects": [
"dammam"
],
"queries": [
"routing",
"get_hull"
],
"routing": [
"driving"
]
}
]
```
Если значение rules не определено, то будут браться значения из файла rules.conf. Если и его нет, то будет ошибка.
=> Include rules as value or file

charts/gis-platform/templates/gis-platform-portal-dep.yaml, charts/gis-platform/templates/gis-platform-spcore-sts.yaml
При новых релизах у конфигмапы/секрета меняется версия хелмчарта в метаданных, из-за этого меняются чексуммы, и сервис перезапускается, даже если в конфиге реально изменений не было. В этом коммите я сделал так, что чексумма считается только от реальных данных, без учёта `metadata:`
=> [gis-platform] Better secret/configmap checksum calculation

charts/catalog-api/Chart.yaml, charts/gis-platform/Chart.yaml, charts/keys/Chart.yaml, charts/mapgl-js-api/Chart.yaml, charts/navi-back/Chart.yaml, charts/navi-castle/Chart.yaml, charts/navi-front/Chart.yaml, charts/navi-router/Chart.yaml, charts/proxy-traffic-jams/Chart.yaml, charts/search-api/Chart.yaml, charts/tiles-api/Chart.yaml
При подготовке 0.2.0 в datagateway не залились докер-образы, релиз опубликовался пустой. Бамп версии для фикса, т.к. фарш невозможно провернуть назад
=> Release 0.2.1

charts/tiles-api/README.md, charts/tiles-api/configs/api.yaml, charts/tiles-api/configs/importer/importer.yaml, charts/tiles-api/values.yaml
Добавил возможность указать название окружения, чтобы сделать несколько окружений на одном кластере кассандры. Теперь название кейспейса зависит от названия окружения
=> [tiles-api] Add cassandra env name to keyspace

charts/tiles-api/Chart.yaml, charts/tiles-api/README.md, charts/tiles-api/configs/importer/importer.yaml, charts/tiles-api/templates/cassandra-cleaner-job.yaml, charts/tiles-api/templates/import.configmap.yaml, charts/tiles-api/values.yaml
Добавлена джоба чистки старый кейспейсов. По-умолчанию выключена, включается через values.importer.cleaner.enabled = true
Появился параметр forceImport (по-умолчанию выключен), который сносит кейспейс, если он совпадает с тем, куда импорты делаются
Добавлены параметры jmxUser/jmxPassword для обращению к nodetool
=> [tiles-api] Cassandra cleaning

charts/navi-back/README.md, charts/navi-back/templates/_helpers.tpl, charts/navi-back/templates/configmap.yaml, charts/navi-back/templates/tests/test-connection.yaml, charts/navi-back/values.yaml
Kafka and D3 sections enable dm-async functionality, these sections added.
The following changes ported from 2GIS version of the chart:
1. bicycle config added
2. support for limits for test-connection job, certain policies might block
creation of resources otherwise
3. setting resources is optional, indexing nil exception avoided if not
specified
4. chart name mismatch in README fixed
5. typo and formatting
Backward compatibility checked on available on-prem properties, resulting helm template diff as expected adds nothing but test-connection limits:
```
$ diff -U0 helm.master-main.yaml helm.fb-main.yaml
--- helm.master-main.yaml	2022-07-21 18:56:37.868556068 +0300
+++ helm.fb-main.yaml	2022-07-21 18:56:19.856529621 +0300
@@ -213,0 +214 @@
+
@@ -398 +399 @@
-        checksum/config: …
```
=> Added support for dm-async

Breaking-Changes.md, charts/gis-platform/README.md, charts/gis-platform/configs/portal/default.conf.template, charts/gis-platform/configs/spcore/SPCore.json.template, charts/gis-platform/configs/spcore/spcore-entrypoint.sh, charts/gis-platform/gis-platform-config/configuration/MapConfig.json, charts/gis-platform/templates/gis-platform-spcore-sts.yaml, charts/gis-platform/templates/gis-platform-websocket-ingress.yaml, charts/gis-platform/values.yaml
> Теперь бакета с юзерпиками previewStorageBucketName больше нет в конфиге, а сами юзерпики переехали в бакет bucketName. В нем должна появиться папка userimage куда нужно перетащить все юзерпики из старого бакета. Также теперь все временные данные хранятся в sessionStorageBucketName - его необходимо создать до обновления. Ключ "provider": "aws" указывает на то, что теперь используется библиотека aws.
=> gis-platform 2022-09-07

charts/license/README.md
Ссылки на нормальную доку пока что всё ещё нет, но текущая ссылка вообще возвращает 404 - пусть лучше будет хотя бы overview.
=> [qfix] Поправил корявую ссылку в README сервиса лицензирования

charts/tiles-api/configs/importer/job.yaml, charts/tiles-api/templates/_helpers.tpl, charts/tiles-api/templates/cassandra-cleaner-job.yaml, charts/tiles-api/templates/deployment.yaml, charts/tiles-api/templates/hpa.yaml, charts/tiles-api/templates/ingress.yaml, charts/tiles-api/templates/job.yaml, charts/tiles-api/templates/pdb.yaml, charts/tiles-api/templates/service.yaml, charts/tiles-api/templates/vpa.yaml
1. Добавил `app.kubernetes.io/component` лейблы для `api`, `importer`, `cleaner`.
2. Добавил selector лейблы во все поды, чтобы их можно было мониторить через:
```sh
$ kubectl get pods -l app.kubernetes.io/instance=on-prem-tiles-api-vector
```
=> IODEV-1145: Tiles-importers добавить лейблы

charts/navi-castle/templates/configmapbuilder.yaml, charts/tiles-api/templates/_helpers.tpl
В Datagateway мы переименовали сервисы:
* routing -> navi
* tiles-api-webgl -> tiles-api-vector
теперь надо смотреть пути до данных в манифесте в этих новых сервисах.
Пока что мы пишем и в старые сервисы, но планируем со временем отказаться от обратной совместимости.
@i-bogomazov посмотри пожалуйста на navi-castle, я правильно у вас поправил? Нигде не пропустил?
=> IODEV-903 Переименовал сервисы для поиска в манифесте

charts/pro-ui/values.schema.json, charts/pro-ui/values.yaml
Добавил values.schema.json, чтобы можно проверить было values по ней при `helm install|lint`. Схема подтянется автоматом, ничего спецом делать не надо. Главное, чтобы файлик с values назывался `values.yaml` и был рядом со схемой.
@Fullmetal8ender
=> Add values.schema.json to pro-ui

charts/tiles-api/templates/import.configmap.yaml
Начиная с `4.43.0` это поле больше не используется - теперь мы берём тип данных из манифеста
=> IODEV-1329: Убрал `data-type` из конфигмапы импортера

charts/mapgl-js-api/README.md, charts/mapgl-js-api/templates/deployment.yaml, charts/mapgl-js-api/values.yaml
Добавил недостающую переменную.
Она бывает полезна, если сервису нужно подложить тайлы из необычного места.
=> Добавил переменную окружения MAPGL_TILESET для MapGL JS API

charts/tiles-api/templates/deployment.yaml
* Тайлсервер умеет сообщать о своём состоянии, но это не проверяется - добавил liveness пробу.
* Тайлсервер не смотрит никакими портами наружу, поэтому readiness проба тут бессмысленна - ей добавлять не стал.
Это нужно для фикса бага с пропадающей после полного рестарта кассандрой.
=> IODEV-1469: Добавил liveness пробу для тайлсервера

charts/tiles-api/templates/deployment.yaml
Мы коллективно не смогли понять, зачем нам нужна здесь эта переменная, и она не даёт клиенту кассандры добавлять новые ноды - поэтому убираем
=> [tiles-api] Removed PEERS_IGNORE env from deployment

charts/mapgl-js-api/README.md, charts/mapgl-js-api/values.yaml
Правка переменной `MAPGL_FLOORSSERVER` для Mapgl JS API. Нужно слить после https://github.com/2gis/on-premise-helm-charts/pull/262.
=> Floorsserver env for mapgl-js-api

charts/license/Chart.yaml, charts/license/README.md, charts/license/templates/NOTES.txt, charts/license/templates/configmap.yaml, charts/license/templates/ingress.yaml, charts/license/templates/secret.yaml, charts/license/templates/service.yaml, charts/license/templates/statefulset.yaml, charts/license/values.yaml
Обновил чарты для license v2.0 (пока что только для TRUSTED).
1. Переделал Deployment на StatefulSet (это будет нужно для TPM, но сразу закладываем это сюда).
2. Переделал порты, теперь есть:
* `statusPort (80)` - страница статуса + api/v1
* `apiPort (443)` - api/v2
3. Добавил persistence - пока что он обязательный, когда будем делать RAFT, сделаем его опциональным.
В целом всё пока что работает как прежде, никаких изменений со стороны клиентов / интегрируемых сервисов.
* `service.port` -> `service.statusPort`
В sandbox с такой конфигурацией:
```yaml
dgctlDockerRegistry: docker-hub.2gis.ru
image:
repository: on-premise/license
tag: 2.0.1
license:
path: license
dgctlStorage:
host: on-prem-minio.default.svc:9000
bucket: datagateway
accessKey: testingkey
secretKey: testingsecret
ingress: …
```
=> IODEV-1350: Чарты для license v2.0

charts/license/README.md, charts/license/templates/configmap.yaml, charts/license/values.yaml
Теперь вместо схемы в `host` используется флаг `secure`, который определяет, по какому протоколу надо общаться с S3.
Можно протестировать на этом образе - `docker-hub.2gis.ru/on-premise/license:2.1.2`
=> IODEV-1545: Добавил secure флаг в настройки S3

charts/tiles-api/README.md, charts/tiles-api/values.yaml
Начиная с версии `4.49.0` мы планируем отказаться от поддержки лицензирования v1 и перейти на лицензирование v2 - соответственно эндпойнт сервиса лицензирования обязательно должен быть `https` эндпойнтом
=> IODEV-1568: [tiles-api] Changed description of license.url param

charts/pro-ui/Chart.yaml, charts/pro-ui/templates/ui/deployment.yaml, charts/pro-ui/values.schema.json, charts/pro-ui/values.yaml
По мотивам долгих бесед с @endryhold и тикета https://jira.2gis.ru/browse/PRO-3260
Обсудили проблему, кажется, IO-спецам не хватает хелсчека у pro-ui, который бы ответил на вопрос, а в фронт или бек сломался. Для этого в приложении завели новый URL, где возвращается инфа по ready-статусу бека и фронта — /api/api/healthcheck/integration
Мы думали, как это отразить в хельме, вот решили в комменте описать. Но для этого путь до основного хелсчека (который в пробах k8s используется), мы вынесли в values.
=> PRO-3260: update helm for pro-ui

Breaking-Changes.md, charts/navi-async-matrix/Chart.yaml, charts/navi-async-matrix/README.md, charts/navi-async-matrix/templates/_helpers.tpl, charts/navi-async-matrix/templates/configmap.yaml, charts/navi-async-matrix/templates/hpa.yaml, charts/navi-async-matrix/templates/role.yaml, charts/navi-async-matrix/templates/rolebinding.yaml, charts/navi-async-matrix/templates/secret.yaml, charts/navi-async-matrix/templates/statefulset.yaml, charts/navi-async-matrix/templates/vpa.yaml, charts/navi-async-matrix/values.yaml
В связи с новыми требованиями безопасности, весь питон код в docker образах dmasync упаковывается в бинарники.
Данные изменения являются ломающими, так как для успешного запуска образов с бандлами вносятся изменения в деплой.
Запуск dmasync сервисов теперь производится внутри docker образов, что повлекло к следующим изменениям:
- dmasync-service теперь не будет запускаться через command.
- параметр ```dm.workerCount``` больше недоступен (нельзя передать в бандл). Вместо этого увеличивается ```replicaCount``` до 2
- добавлен параметр ```dm.host``` принимает значения вида: ```0.0.0.0``` и вместе с ```dm.port``` пробрасывается через переменные ```DM_ASYNC_SERVICE_HOST``` и ```DM_ASYNC_SERVICE_HOST``` в деплой.
- параметризирована DB схема, чтобы появилась возможность использования не …
=> Add bundilng python code for dmasync + DB schema parameter

charts/navi-front/templates/configmap-extra.yaml
To master.
Fix name for configmap extra. Need for locationsBlock value location: pedestrian MSDK
=> mfront fix name configmap-extra to master

charts/navi-front/templates/configmap-extra.yaml
Fix name for configmap extra. Need for locationsBlock value location: pedestrian MSDK
=> mfront fix name configmap-extra

Breaking-Changes.md, charts/navi-router/Chart.yaml, charts/navi-router/README.md, charts/navi-router/templates/configmap.yaml, charts/navi-router/templates/deployment.yaml, charts/navi-router/templates/ingress.yaml, charts/navi-router/templates/secret.yaml, charts/navi-router/values.yaml
API keys are moved out of config to secrets
commonToken can be used as a master token to retrieve all per-service keys from the key service
`router.keyManagementService.apis.*` keys renamed, `-api` suffix added
=> API keys moved to secrets

charts/navi-castle/README.md, charts/navi-castle/templates/configmapbuilder-runnable.yaml, charts/navi-castle/templates/configmapbuilder.yaml, charts/navi-castle/templates/cronjob.yaml, charts/navi-castle/templates/statefulset.yaml, charts/navi-castle/values.yaml
Ранее:
- Если выключить кроны, то не импортируем данные на старте
- Если выключен PVC и выключены кроны - получаем пустой castle при перезапуске
Теперь:
- Можно управлять что именно ипортируем при старте
- Можно импортировать данные на старте, но не включать кроны
=> NAVI-CASTLE: bugfix init import data

charts/navi-async-matrix/README.md, charts/navi-async-matrix/templates/_helpers.tpl, charts/navi-async-matrix/templates/configmap.yaml, charts/navi-async-matrix/templates/role.yaml, charts/navi-async-matrix/templates/rolebinding.yaml, charts/navi-async-matrix/templates/secret.yaml, charts/navi-async-matrix/templates/statefulset.yaml, charts/navi-async-matrix/values.yaml
Default behavior preserved. In addition to that it is supported to set or override Kafka parameters for
producer and consumer individually.
=> Support for separate Kafka properties

charts/catalog-api/templates/helpers.tpl
Removed outdated startup environment options for the Catalog API service
=> Catalog: no useless db keys envs

charts/citylens/Chart.yaml, charts/citylens/templates/web/configmap.yaml, charts/citylens/values.yaml
Changelog:
* OpenId Connect (OIDC): поддержка PKCE, поддержка работы с OpenID Provider не требующего указания realm
* Поддержка мультиязычного рендеринга детекций на кадрах в Про
* CamCom: логгирование в БД ответов API, дашборд со статистикой, передача в API CamCom данных о картинке на s3 вместо самой картинки кадра
* Синхронизация с Про на уровне кадров трека (ранее - только все кадры трека одновременно) при загрузке кадра и сохранении детекций с кадра.
* Работа с S3: ACL public-read по умолчанию больше не проставляется для бакетов с кадрами. S3 ключ кадра теперь имеет вид `uuid трека/timestamp кадра.jpg` (убран e-mail пользователя, координаты кадра, дата)
=> Update citylens chart for version 1.2.0

Breaking-Changes.md, charts/license/Chart.yaml, charts/license/README.md, charts/license/templates/configmap.yaml, charts/license/templates/secret.yaml, charts/license/templates/statefulset.yaml, charts/license/values.yaml
С обновлением сервиса лицензирования до `2.2.0` произошли несколько ломающих изменений, которые тут отразил:
1. убрали поддержку persistence через PVC - оставили только S3, соответственно теперь конфигмапа и values выглядят немного по-другому,
2. убрали обратную совместимость с лицензией v1 - теперь будем принимать только лицензию v2.
> Влияет ли это как-то на использование `/api/v1`?
Нет - `/api/v1` теперь просто работает поверх лицензии v2, с этой стороны ничего не изменилось.
> На что это влияет вообще?
Если после обновления в контуре будет только старая лицензия, которая пишется в `datagateway:/license`, то сервис лицензирования никак не будет её использовать и всё сломается.
> Что делать, если у клиента супер старая версия, в которой нет файла с лицензией v2?
Надо сначала обновиться …
=> IODEV-1748: Обновление сервиса лицензирования

charts/license/README.md, charts/license/templates/_helpers.tpl, charts/license/templates/custom-ca.configmap.yaml, charts/license/templates/statefulset.yaml, charts/license/values.yaml
Добавил возможность использования кастомных CA - честно всё скопировал из https://github.com/2gis/on-premise-helm-charts/pull/371.
Не стал мешать с другим открытым ПРом для `license` - они никак не зависят друг от друга.
Надо запустить minio с TLS, я делал это вот так:
```yaml
ingress:
enabled: true
annotations:
nginx.ingress.kubernetes.io/proxy-body-size: 1024m
nginx.ingress.kubernetes.io/ssl-redirect: "false"
hosts:
- minio.${CLUSTER_DOMAIN}
tls:
- secretName: minio-tls
hosts:
- minio.${CLUSTER_DOMAIN}
```
Соответственно надо подготовить `tls` секрет.
Сервис лицензирования должен ходить по правильному адресу и с указанием TLS:
```yaml
dgctlStorage:
host: minio.${CLUSTER_DOMAIN}:443
secure: true
```
Изменения в коде не подразумеваются, можно взять соответствующий для `1.16.0` образ и …
=> IODEV-1763: Добавил возможность использования кастомных CA в license

charts/navi-castle/README.md, charts/navi-castle/templates/statefulset.yaml, charts/navi-castle/values.yaml
В случае, когда данные импортируются долго, инициализация контейнера превышает тайминги `livenessProbe` и castle невозможно запустить.
Добавлен параметризованный startupProbe.
=> navi-castle: startup probe added

Breaking-Changes.md, charts/citylens/templates/api/configmap.yaml, charts/citylens/templates/api/deployment.yaml, charts/citylens/templates/web/configmap.yaml, charts/citylens/templates/web/deployment.yaml, charts/citylens/values.yaml
Changelog:
* citylens-api:
* authorization: check token exipiry via auth service
* authorization: add support for auth on camcom callback endpoint 
* request validation: expect frames with same email as current user
* prometheus metrics: added citylens-api:8001/healthz/metrics endpoint
* citylens-web:
* prometheus metrics: added citylens-web:5001/healthz/metrics endpoint
=> Update citylens chart for version 1.3.0

charts/license/Chart.yaml, charts/license/README.md, charts/license/templates/statefulset.yaml, charts/license/values.yaml
В `2.2.1` мы поменяли дефолтного пользователя в контейнере сервиса лицензирования с `root` на `1234`. Для работы с TPM нужен `root` пользователь, поэтому теперь для `license.type: 2` обязательно должен проставляться `securityContext` с `root` пользователем.
Соответственно немного поменял чарты:
1. убрал из values `tpm.securityContext` - тут больше не нужна вариативность,
2. переделал блок `securityContext` в STS, чтобы для `license.type: 2` выбирался `root` пользователь:
```yaml
securityContext:
runAsUser: 0
runAsGroup: 0
```
3. для прямого монтирования TPM (не через девайс плагин) дополнительно выставляется `privileged` флаг:
```yaml
securityContext:
runAsUser: 0
runAsGroup: 0
privileged: true
```
Можно тестировать с образом `2.2.1`.
=> IODEV-1762: Поправил securityContext для license

charts/pro-api/Chart.yaml, charts/pro-api/README.md, charts/pro-api/templates/deployment.yaml, charts/pro-api/values.yaml, image_versions.txt
Основные изменения в Pro API:
- [PRO-4106 Включить UI сервиса пермиссий в он-прем поставке](https://jira.2gis.ru/browse/PRO-4106)
- [PRO-3205 Поддержка NOT фильтров](https://jira.2gis.ru/browse/PRO-3205)
- [PRO-3809 Добавить ассетам поле с group id](https://jira.2gis.ru/browse/PRO-3809)
- [PRO-3981 Убрать символы $.[''] в названии полей при парсинге geojson](https://jira.2gis.ru/browse/PRO-3981)
- [PRO-4074 Научиться выбирать районы в РФ](https://jira.2gis.ru/browse/PRO-4074)
- [PRO-3094 Добавление точечных данных в загруженный ассет](https://jira.2gis.ru/browse/PRO-3094)
- [PRO-3281 Сделать email уникальным атрибутом пользователя](https://jira.2gis.ru/browse/PRO-3281)
- [PRO-3969 Cохранения текущего стиля карты в группу слоев](https://jira.2gis.ru/browse/PRO-3969)
- [PRO-4066 Поддержка …
=> [PRO-4361] Обновление pro-api до версии 1.1.79

charts/pro-ui/Chart.yaml, charts/pro-ui/templates/_helpers.tpl, charts/pro-ui/values.schema.json, charts/pro-ui/values.yaml
Добавлена возможность задать необходимые scopes для openid-провайдера по просьбе Дениса Яковлева для релиза в Momrah, так как им нужны свои скоупы, не те, что захардкожены у нас в коде.
Подробнее тут: https://jira.2gis.ru/browse/PRO-4176
___
___
pro-ui: https://tsup.2gis.dev/pro/pro-ui/changelog/1.5.0..1.7.5
+ https://gitlab.2gis.ru/webdev/urbi-geo/-/releases/Release_2023_12_04_08_23 (релиз до ЦУПа)
**UI:**
1) Добавление даты для карточки в библиотеке (если включена библиотека в онпреме, я так и не понял это) https://jira.2gis.ru/browse/PRO-3468
2) Добавлена возможность задать список scopes для openid-connect Переменная в helm — oAuthScopes (https://jira.2gis.ru/browse/PRO-4176)
3) В настройках визуализации изохрона выводим его опции в иконке рядом с названием ассета …
=> PRO-4176: add auth scopes

charts/navi-castle/templates/configmapbuilder-runnable.yaml, charts/navi-castle/templates/configmapbuilder.yaml
- scheduled tasks without PV
- configuration parameters mistaken
=> navi-castle: bugfix

charts/navi-front/templates/configmap-base.yaml
Синхронизировал дефолтные локейшены в конфиге фронта с теми API, которые заявлены у нас в документации.
Вынес всё кроме get_hull из-под условия на hullLocation. Возможно это условие можно вообще выкосить
=> [DEVOPS-982] navi-front: update default locations

charts/pro-api/templates/asset-import-starter.yaml, charts/pro-api/templates/asset-importer.yaml, charts/pro-api/templates/asset-preparer.yaml, charts/pro-api/templates/deployment.yaml, charts/pro-api/templates/user-asset-importer.yaml, charts/pro-api/values.yaml
Основные изменения в Pro API:
- [PRO-3449 Генерировать ключи для шаринга в онпреме](https://jira.2gis.ru/browse/PRO-3449)
- [PRO-4437 Добавить параметр region к dgctlStorage](https://jira.2gis.ru/browse/PRO-4437)
- [PRO-4234 500 при передаче двух одинаковых атрибутов](https://jira.2gis.ru/browse/PRO-4234)
- [PRO-4498 Не отображаются фильтры в ассете Frames](https://jira.2gis.ru/browse/PRO-4498)
- [PRO-4488 400 При генерации слоя с агрегатами](https://jira.2gis.ru/browse/PRO-4488)
- [PRO-4443 Включить отображение территорий в системных ассетах](https://jira.2gis.ru/browse/PRO-4443)
- [PRO-4511 Авторизованное получение подготовленных данных слоя](https://jira.2gis.ru/browse/PRO-4511)
- [PRO-4627 Добавить параметр для отключения PayloadSigning в …
=> [PRO-4517] Обновление pro-api до версии 1.5.0

charts/pro-api/Chart.yaml, charts/pro-api/README.md, charts/pro-api/values.yaml, image_versions.txt
Хотфикс проблемы: https://mm.2gis.one/2gis-rd/pl/kmpms8cu1jyfjdcdn3g5jb5qow
>  в pro-api версии 1.5.0 обнаружен баг: при чтении данных из стриминговых ассетов, которые из кафки, происходит лишнее экранирование символов, в итоге получаем вот такое некрасивое что то (см. картинку). Баг поправили, тестируем, будем выпускать фикс в ближайшее время.
Проверить так:
1. Должен быть доступ к ассету `momrah_pollution`
2. Открыть загруженный фрейм. Например:
```
/search/assetId/momrah_pollution/filters/territories-%7B"value"%3A"1"%2C"value_type"%3A"list"%7D%3Bdatetime_utc-%7B"value"%3A"2024-02-27T00%3A00%3A00.000Z%2C2024-02-27T00%3A00%3A00.000Z"%2C"value_type"%3A"date_range"%7D/tab/list/entity/momrah_pollution_6573797/37.596345%2C55.574494/momrah_pollution?m=38.172981%2C55.677585%2F9.24
```
ОР: …
=> PRO-0: upgrade PRO API to 1.5.1

Breaking-Changes.md, charts/citylens/Chart.yaml, charts/citylens/templates/api/configmap.yaml, charts/citylens/templates/helpers.tpl, charts/citylens/templates/web/configmap.yaml, charts/citylens/templates/worker/deployment-reporter-pro-tracks.yaml, charts/citylens/values.yaml
Changelog:
- licensing server required (`.Values.api.licensing`)
- running as non-root user in container
- tile server required (`.Values.map.tileserverUrlTemplate`)
- new reporter-pro-tracks worker (required)
- citylens-database:
- running as non-root user in container
min_data_verson: 2
max_data_version: 2
=> Citylens 1.6.0

Breaking-Changes.md, charts/navi-router/README.md, charts/navi-router/templates/_helpers.tpl, charts/navi-router/templates/configmap.yaml, charts/navi-router/templates/deployment.yaml, charts/navi-router/templates/secret.yaml, charts/navi-router/values.yaml
**Changelog**:
Приведение чарта в соответсвие со стайлгайдом
- Секция `router.keyManagementService` переименована в `keys`
- То, что раньше было `router.keyManagementService.host` теперь называется `keys.url`
- Параметр `router.castleHost` переименован в `router.castleUrl`
**Issues**:
https://jira.2gis.ru/browse/DEVOPS-1042
**Для девопсов онпрема**: в чарте добавлена проверка на старые параметры в values. Если это будет срелять в onprem-deploy, то можно отключить, добавив (незадокументированный) параметр
```yaml
debug:
disableDeprecationChecks:
1.19.0: true
```
=> [navi-router] rename router.keyManagementServices to keys

charts/keys/Chart.yaml, charts/keys/README.md, charts/keys/templates/api/deployment.yaml, charts/keys/templates/helpers.tpl, charts/keys/values.yaml
Changelog:
- Добавлена конфигурация для включения аудит логгирования (фича-флаг, настройки клиента кафки)
Issues:
- [WAPI-23317](https://jira.2gis.ru/browse/WAPI-23317)
- [WAPI-23469](https://jira.2gis.ru/browse/WAPI-23469)
Steps for check:
- Включить аудит флагом `featureFlags.enableAudit`, заполнить настройки клиента `kafka.audit`
- В админке ключей пройти аутентификацию, создать ключ
- Проверить, что в топик кафки пришли два сообщения: об аутентификации и о создании ключа соответственно
[Breaking-Changes](../Breaking-Changes.md)
=> WAPI-23469 Add configuration for audit logging

Breaking-Changes.md, charts/citylens/Chart.yaml, charts/citylens/templates/web/configmap.yaml, charts/citylens/templates/worker/deployment-reporter-pro-tracks.yaml, charts/citylens/values.yaml
Changelog:
* citylens-web:
* Fix detection attributes synchronization with Pro
* new table for Pro-related translations instead of multiple `name_localized` columns
* citylens-api:
* better predictions validation on `/api/1.0/predictions/{predictor}` endpoint
min data version: 3
max data version: 3
Breaking changes:
worker.reporterProTracks.replicas` replaced with `worker.reporterProTracks.enabled`. One replica will be deployed if enabled.
=> Citylens 1.7.0

charts/navi-castle/README.md, charts/navi-castle/templates/configmapbuilder.yaml, charts/navi-castle/values.yaml
Changelog:
- Новая версия navi-castle
Раньше данные для `navi-restrictions` выгружались в датагейтвей как данные отдельного сервиса, теперь мы их публикуем как тип данных `resttrictions` в сервисе `navi`.
=> [DEVOPS-1025] Новый castle для новых перекрытий

.github/pull_request_template.md, Breaking-Changes.md, charts/citylens/Chart.yaml, charts/citylens/templates/api/configmap.yaml, charts/citylens/templates/web/configmap.yaml, charts/citylens/values.yaml
- Use same topic for manual and camcom predictions
- Fix problem with excess connections and reconnections to Kafka in citylens-web and some of the workers
- Misc UI enhancements (e.g. better filters on /frames page)
- FR-30, FR-31 (CR 29.02.24)
- Please see changes in [Breaking-Changes](../Breaking-Changes.md)
=> Update citylens chart to 1.8.0 version

charts/citylens/templates/web/configmap.yaml
- citylens-web
- Add missing default value for `.Values.kafka.predictorsExtraTopics` to config template (in configmap)
=> Add missing default for enabled_modules->predictors in citylens-web configmap

charts/pro-ui/README.md, charts/pro-ui/templates/_env.tpl, charts/pro-ui/values.schema.json, charts/pro-ui/values.yaml
Changelog:
- Pro-UI: External Style Manager feature flag configuration option added
- Pro-UI: Mapbox external style public key configuration option added
Issues:
- PRO-4272
- PRO-4270
Old PR (closed): https://github.com/2gis/on-premise-helm-charts/pull/413
=> pro-ui: New external style manager config

charts/keys/Chart.yaml, charts/keys/README.md, charts/keys/templates/helpers.tpl, charts/keys/templates/secret-deploys.yaml, charts/keys/values.yaml
Добавлены новые параметры:
- `featureFlags.enablePublicAPISign` - управляем наличием подписи ответа в методах Public API.
- `api.signPrivateKey` - сам приватный ключ, которым будет подписываться ответ.
- [WAPI-23482](https://jira.2gis.ru/browse/WAPI-23482)
=> WAPI-23482 Add configuration for Public API sign

charts/citylens/templates/web/deployment.yaml
- Add ability to add extra env vars to citylens-web deployment
=> Add ability to add extra env vars to citylens-web deployment

Breaking-Changes.md, CHANGELOG.md, charts/catalog-api/README.md, charts/catalog-api/templates/helpers.tpl, charts/catalog-api/values.yaml
- Добавлены настройки кол-ва коннектов с search-api в catalog-api
- `WAPI-23606` (https://jira.2gis.ru/browse/WAPI-23606)
=> WAPI-23606 catalog search config

charts/platform/Chart.yaml, charts/platform/README.md, charts/platform/templates/ui/deployment.yaml, charts/platform/values.yaml
Образ [тут](https://docker-hub.2gis.ru/harbor/projects/163/repositories/platform-ui/artifacts-tab/artifacts/sha256:0f42de58fcb404d7c3f369fed0346f1f5c3bb667fc7a2a4e36c2a87b54db59b6?sbomDigest=)
https://tsup.2gis.dev/gefest/gefest/changelog/0.9.0..0.15.0
- Исправлена ошибка с пропадающим маркером в песочнице Geocoder API (https://jira.2gis.ru/browse/GEFEST-230)
<details><summary>Details</summary>
<p>
1. восстановиться https://platform-2gis.web-staging.2gis.ru/playground/geocoder
2. ввести поисковой запрос cafe
3. переключить вкладку на Reverse
4. клик в первый пункт в поисковой выдаче
ОР: показали на карте маркер, сдвинули карту
5. клик в карту
ОР: в месте клика появился маркер, сдвинули карту, новая список айтемов
ФР: в месте клика нет маркера, сдвинули карту, новая список айтемов
</p> …
=> Platform 0.15.0

Breaking-Changes.md, charts/navi-async-matrix/README.md, charts/navi-async-matrix/templates/statefulset.yaml, charts/navi-async-matrix/values.yaml
Заготовка ПР под релиз navi-async-matrix 1.11
- Появилась возможность задавать схему для `s3.publicNetloc`
- Фикс подключения к кафке с использованием mTLS
- TRAFFIC-17621
- DEVOPS-663
- Параметр `s3.publicNetloc` теперь обязан содержать схему, `http://` или `https://`
=> [navi-async-matrix] netloc must start with scheme

charts/navi-back/Chart.yaml, charts/navi-back/README.md, charts/navi-back/templates/configmap.yaml, charts/navi-back/values.yaml
- Исправлено падение Моисея при попытке обновления движков в процессе завершения работы сервиса.
- Максимальное время проезда sharing-маршрутов сохраняется в Kafka.
- Произведена небольшая очистка логов от шума.
- Исправлен баг с конфигурацией префикса при логгировании в json режиме.
- Поддержаны идентификаторы карточек для барьеров.
- Обработка онлайн скоростей полностью переведена на float тип данных.
- В Isochrone, DistanceMatrix параметр mode переименован на transport с поддержкой обратной совместимости.
- В строке запроса Pairs, а также в RoutingV7 в поле transport измененены поля: car -> driving, pedestrian -> walking с поддержкой обратной совместимости.
- В поиске с промежуточными точками теперь выбирается лучший промежуточный маршрут по стоимости, а не по времени.
- Поддержан учет …
=> [chart/navi-back] chart syncup

charts/stat-receiver/README.md, charts/stat-receiver/configs/streams/application.conf.template, charts/stat-receiver/templates/api/configmap.yaml, charts/stat-receiver/templates/api/deployment.yaml, charts/stat-receiver/templates/api/ingress.yaml, charts/stat-receiver/templates/api/service.yaml, charts/stat-receiver/templates/helpers.tpl, charts/stat-receiver/templates/streams/configmap.yaml, charts/stat-receiver/templates/streams/deployment.yaml, charts/stat-receiver/templates/streams/headless-service.yaml, charts/stat-receiver/values.yaml
- Fix error in template streams/application.conf
- Change naming from bss-receiver to stat-receiver 
- `ONPREM-843`
=> Change variables naming

charts/citylens/Chart.yaml, charts/citylens/README.md, charts/citylens/values.yaml
- Improved stability of frame upload endpoint for new mobile app (POST /api/1.0/routes/{track_uuid}/frame)
none
none
=> Citylens 1.13.0

charts/license/Chart.yaml, charts/license/README.md, charts/license/templates/configmap.yaml, charts/license/values.yaml
- Поправили логику формирования файлов для запроса лицензии - теперь если их нет, то они синхронно создаются во время запуска приложения (раньше это делалось асинхронно и приложение могло завершиться до того, как они были бы сформированы).
- Поддержали параметр `region` для конфигурации S3.
- [GEFEST-954](https://jira.2gis.ru/browse/GEFEST-954)
- [GEFEST-1073](https://jira.2gis.ru/browse/GEFEST-1073)
=> [license] Upgraded app version to 2.2.3

charts/navi-async-matrix/README.md, charts/navi-async-matrix/templates/_helpers.tpl, charts/navi-async-matrix/templates/configmap-ca.yaml, charts/navi-async-matrix/templates/statefulset.yaml, charts/navi-async-matrix/values.yaml, charts/navi-castle/README.md, charts/navi-castle/templates/_helpers.tpl, charts/navi-castle/templates/configmap-ca.yaml, charts/navi-castle/templates/cronjob.yaml, charts/navi-castle/templates/statefulset.yaml, charts/navi-castle/values.yaml, charts/navi-restrictions/README.md, charts/navi-restrictions/templates/_helpers.tpl, charts/navi-restrictions/templates/configmap-ca.yaml, charts/navi-restrictions/templates/cronjob.yaml, charts/navi-restrictions/templates/deployment.yaml, charts/navi-restrictions/values.yaml
- add custom ca for navi-castle, navi-restrictions, navi-async-matrix
- [DEVOPS-1360](https://jira.2gis.ru/browse/DEVOPS-1360)
=> add custom ca for navi-castle, navi-restrictions, navi-async-matrix

charts/gis-platform/README.md, charts/gis-platform/templates/gis-platform-websocket-ingress.yaml, charts/gis-platform/values.yaml
- websocket-services должен указывать на backend.service.name
Надо проверить что валидация ingress проходит без ошибок и что веб-сокет работает.
- Обязательные дефолтные значения в пустую строку согласно styleguide
=> [EVERGIS] websocket-services должен указывать на backend.service.name. Required defaults

charts/traffic-proxy/README.md, charts/traffic-proxy/templates/configmap.yaml, charts/traffic-proxy/values.yaml
Update traffic-proxy chart configuration and nginx template
- Add worker processes and connections settings
- Implement customizable log formats and paths
- Allow custom location definitions
- ONPREM-1033
=> [traffic-proxy] Update traffic-proxy chart configuration and nginx template

charts/stat-receiver/README.md, charts/stat-receiver/configs/api/application.conf.template, charts/stat-receiver/configs/api/logback.xml.template, charts/stat-receiver/configs/streams/application.conf.template, charts/stat-receiver/configs/streams/logback.xml.template, charts/stat-receiver/templates/api/configmap.yaml, charts/stat-receiver/templates/streams/configmap.yaml, charts/stat-receiver/values.schema.json, charts/stat-receiver/values.yaml
-  Добавил logLevel + проброс в конфиг приложения
-  Добавил initializeTopics.enabled и topicsPrefix в values + описал
- `ONPREM-166`
- initializeTopics renamed to initializeTopics.enabled
=> [stat-receiver] Refactoring by styleguide 

charts/catalog-api/README.md, charts/catalog-api/templates/api/deployment.yaml, charts/catalog-api/templates/importer/cleaner/job.yaml, charts/catalog-api/templates/importer/job.yaml, charts/catalog-api/values.yaml
- `Добавлен проброс поля securityContext в chart catalog-api`
- `WAPI-23770` (https://jira.2gis.ru/browse/WAPI-23770)
=> WAPI-23770 поддержка securityContext в catalog api

charts/citylens/Chart.yaml, charts/citylens/README.md, charts/citylens/templates/helpers.tpl, charts/citylens/templates/web/configmap.yaml, charts/citylens/templates/web/workers/deployment-map-matcher.yaml, charts/citylens/templates/workers/configmap.yaml, charts/citylens/values.yaml
- Added support for Map Matching of tracks & frames (see `.Values.worker.mapMatcher`)
- Fixed precision of driver distance in km at Drivers asset in Pro
=> Bump citylens to 1.16

charts/floors-api/README.md, charts/floors-api/values.yaml, charts/search-api/README.md, charts/search-api/values.yaml, charts/traffic-proxy/README.md, charts/traffic-proxy/values.yaml
- Update nginx version 1.25.4 -> 1.25.5
- n/a
- n/a
=> [search, floors, traffic] Update nginx version 1.25.4 -> 1.25.5

.github/workflows/release-oci.yaml
- `ONPREM-1388` (Link to related issue)
=> Информативное описание workflow GHA

charts/keys/README.md, charts/keys/values.yaml, image_versions.txt
Релизить вместе с keys-api: https://github.com/2gis/on-premise-helm-charts/pull/537
https://tsup.2gis.dev/gefest/keys-admin/changelog/0.8.1..0.10.3
- Поправлен баг, при котором клик в алерт закрывал модалку
> Если открыто модальное окно, то при закрытии алерта, закрывается и модальное окно.
- https://jira.2gis.ru/browse/GEFEST-1325
=> GEFEST-1325: up keys-ui to 0.10.3

Breaking-Changes.md, charts/keys/templates/import/job.yaml
- В джобу импорта временно добавлено использование флага `--migrate-data`
- Версия образа остаётся из другого МР (на него смотрит текущий) 1.108.2
- https://jira.2gis.ru/browse/GEFEST-1341
- Добавлена информация про флаг и необходимость обновления Сервиса Ключей перед обновлением сервисов Navi.
=> GEFEST-1341 В чарт Keys в джобу импорта добавлен временный флаг для дата-миграции

charts/navi-back/Chart.yaml, charts/navi-back/README.md, charts/navi-back/templates/configmap.yaml, charts/navi-back/values.yaml
depends on https://github.com/2gis/on-premise-helm-charts/pull/584
- https://tsup.2gis.dev/navi/moses/7.33.0
- ETA schedule index parameterized
- traffic lights section for future releases added
- n/a
=> navi back 7.33.0.5 release

Breaking-Changes.md, charts/navi-castle/Chart.yaml, charts/navi-castle/README.md, charts/navi-castle/templates/_helpers.tpl, charts/navi-castle/templates/configmapbuilder.yaml, charts/navi-castle/templates/configmapnginx.yaml, charts/navi-castle/templates/cronjob.yaml, charts/navi-castle/templates/secret.yaml, charts/navi-castle/templates/service.yaml, charts/navi-castle/templates/statefulset.yaml, charts/navi-castle/values.yaml
- `navi-castle` 1.9.8 release: https://tsup.2gis.dev/navi/castle/1.9.8
- fast restrictions distribution support added for future uses, not fully available yet
- projects excluding list supported, refer to `castle.excludeProjects` property
- data retention is now configurable, refer to `castle.storePeriod` property
- ephemeral persistent volume support added
- n/a
- n/a
=> navi-castle 1.9.8

charts/navi-attractor/.helmignore, charts/navi-attractor/Chart.yaml, charts/navi-attractor/README.md, charts/navi-attractor/templates/NOTES.txt, charts/navi-attractor/templates/_helpers.tpl, charts/navi-attractor/templates/configmap.yaml, charts/navi-attractor/templates/deployment.yaml, charts/navi-attractor/templates/hpa.yaml, charts/navi-attractor/templates/ingress.yaml, charts/navi-attractor/templates/pdb.yaml, charts/navi-attractor/templates/secret.yaml, charts/navi-attractor/templates/service.yaml, charts/navi-attractor/templates/serviceaccount.yaml, charts/navi-attractor/templates/vpa.yaml, charts/navi-attractor/values.yaml
- part of `navi-back` functionality implemented as a separate service, required for DMA for Trucks
- none
=> [chart/navi-attractor] chart syncup

charts/keys/templates/api/deployment.yaml
- Добавил preStop хук для API, чтобы был у нас graceful shutdown (дообрабатывались все текущие запросы и только потом под терминировался). На стороне приложения поддержать эту логику дорого, поэтому делаем так.
- Так же выставил terminationGracePeriodSeconds в 60 секунд, чтобы было с запасом (по дефолту 30).
- [GEFEST-1481](https://jira.2gis.ru/browse/GEFEST-1481)
=> GEFEST-1481 Добавил preStop хук для api в чарте Keys

charts/citylens/Chart.yaml, charts/citylens/README.md, charts/citylens/values.yaml
- Routes Planner integration: fix /routes-api proxy endpoint (used by mobile app for accessing Routes Planner API)
- `CV-108`
=> Bump citylens-api to 1.17.9: fix routes api proxy endpoint

charts/navi-vrp-solver/.helmignore, charts/navi-vrp-solver/Chart.yaml, charts/navi-vrp-solver/README.md, charts/navi-vrp-solver/templates/NOTES.txt, charts/navi-vrp-solver/templates/_helpers.tpl, charts/navi-vrp-solver/templates/deployment.yaml, charts/navi-vrp-solver/templates/hpa.yaml, charts/navi-vrp-solver/templates/ingress.yaml, charts/navi-vrp-solver/templates/pdb.yaml, charts/navi-vrp-solver/templates/secret.yaml, charts/navi-vrp-solver/templates/service.yaml, charts/navi-vrp-solver/templates/serviceaccount.yaml, charts/navi-vrp-solver/templates/vpa.yaml, charts/navi-vrp-solver/values.yaml, charts/navi-vrp-task-manager/.helmignore, charts/navi-vrp-task-manager/Chart.yaml, charts/navi-vrp-task-manager/README.md, charts/navi-vrp-task-manager/templates/NOTES.txt, charts/navi-vrp-task-manager/templates/_helpers.tpl, charts/navi-vrp-task-manager/templates/deployment.yaml, charts/navi-vrp-task-manager/templates/hpa.yaml, charts/navi-vrp-task-manager/templates/ingress.yaml, charts/navi-vrp-task-manager/templates/pdb.yaml, charts/navi-vrp-task-manager/templates/secret.yaml, charts/navi-vrp-task-manager/templates/service.yaml, charts/navi-vrp-task-manager/templates/serviceaccount.yaml, charts/navi-vrp-task-manager/templates/vpa.yaml, charts/navi-vrp-task-manager/values.yaml
- new services added: VRP solver and VRP task manager
- n/a
- n/a
internal documentation for VRP/TSP available:
https://confluence.2gis.ru/pages/viewpage.action?pageId=389323516
=> VRP solver & task-manager

charts/pro-ui/README.md, charts/pro-ui/templates/_env.tpl, charts/pro-ui/values.schema.json, charts/pro-ui/values.yaml
- Появилось новое поле ui.zenith.hasAdmDivsLayers. Оно опциональное, по умолчанию имеет значение false. Переменная сигнализирует о наличии слоев adm_div на сервере Zenith. Требуется для функции «выбрать территории на карте».
- Добавлены подписи для графиков (Для Столбчатых, Линейных и Гистограмм)
- Визуальные улучшения интерфейса для пользователей браузера Safari
- Была реализована поддержка нового формата для вывода диапазонов по годам в виджете-легенде.
- Виджеты без доступа к данным теперь явно сообщают об этом пользователю
- Добавлена возможность выбора двух атрибутов для группировки при построении графиков и диаграмм
- Выводим график типа "Пирамида" для ассета "Половозрастная структура населения".
- В сообщениях в логах теперь отправляется версия приложения
- Увеличили время показа …
=> [PRO-8197] Релиз PRO-UI 4.19.0
